services:
  web:
    environment:
      - APP_ENV=local
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./src:/var/www/html

  db:
    image: mysql:latest
    container_name: mysql_php_taskflow
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskflow
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/conf.d/my.cnf

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_php_taskflow
    ports:
      - '8083:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    command: >
      sh -c "echo 'ServerName localhost' >> /etc/apache2/apache2.conf && apache2-foreground"
    depends_on:
      - db

volumes:
  db_data:
