services:
  web:
    container_name: php_apache_taskflow
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8082:80'
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      APP_ENV: production

volumes:
  web_data:
    external: true