services:
  web:
    container_name: php_apache_taskflow
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8082:80'
    volumes:
      - web_data:/var/www/html
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      APP_ENV: ${APP_ENV}
    entrypoint: /usr/local/bin/entrypoint.sh

volumes:
  web_data:
  db_data:
